const fs = require('fs');

// Vercel inyecta las variables de entorno en process.env durante el build
const apiUrl = process.env.VITE_API_URL || process.env.API_URL || 'https://TU_API_EN_RENDER/api';

const envContent = `// Production environment - Auto-generated by deployment script
// DO NOT EDIT MANUALLY - This file is generated during build
export const environment = {
    production: true,
    apiUrl: '${apiUrl}'
};
`;

const envFilePath = './src/environments/environment.ts';

try {
    fs.writeFileSync(envFilePath, envContent);
    console.log('✅ Environment configurado exitosamente');
    console.log('📍 API URL:', apiUrl);
} catch (error) {
    console.error('❌ Error al configurar environment:', error);
    process.exit(1);
}
